### ISSUE TITLE
Doesnt work anymore

### ISSUE THREAD

**Issue by genert** [i18next/i18next-fluent#1]
This library does not work anymore as this line fails - https://github.com/i18next/i18next-fluent/blob/master/src/index.js#L66

**Comment by jamuhl** [comment]
Need more details...i18next.languages is empty there...can't be after initializing at least not if either you set a lng on init or use the browser-languagedetector....

**Comment by oasalonen** [comment]
I'm able to reproduce this issue server-side where I'm using i18nextMiddleware.LanguageDetector in a node.js express app. My i18next init looks like this:

```js
    i18next
        .use(i18nextMiddleware.LanguageDetector)
        .use(FilesystemBackend)
        .use(Fluent)
        .init({
            debug: true,
            fallbackLng: 'en',
            preload: ['en', 'de'],
            ns: ['translation', 'my.namespace'],
            detection: {
                order: ['cookie', 'querystring', 'header'],
                lookupCookie: 'lang'
            },
            backend: {
                loadPath: path.join(__dirname, '..', '..', 'client', 'build', 'locales/{{lng}}/{{ns}}.ftl'),
                parse: function(data) {
                    return ftl2js(data);
                }
            }
        });
```
It works if I set the `lng` option, but then that bypasses the language detection.

**Comment by jamuhl** [comment]
On serverside that can't really work...not this way...language detection happens during request - not on init -> there is also not the main instance used but a cloned instance on request!!!

So https://github.com/i18next/i18next-fluent/blob/master/src/index.js#L66 has to be done based on languages in preload.

A PR would be very welcome...

**Comment by genert** [comment]
@oasalonen  If memory serves correctly I think that was the issue. 

BTW, been using this library since this issue was created so kudos @jamuhl for creating this library!

**Comment by jamuhl** [comment]
thank you both for making this module better 👍
