### ISSUE TITLE
[zero] is translated as [other]

### ISSUE THREAD

**Issue by Cesco9525** [i18next/i18next-fluent#2]
Hi guys, I'm implementing a translation system in a React web app using typescript, react-18next and i18next-fluent. My problem is that in .ftl files just [one] and [other] options are considered. When I try to create an exception for 0 by specifying it in the .ftl file using [zero] or [0], the translation is the same as [other].

This is my i18n.ts file:

```
import i18n from 'i18next';
import LanguageDetector from 'i18next-browser-languagedetector';
import { initReactI18next } from 'react-i18next';
import Fluent from 'i18next-fluent';
import Backend from 'i18next-fluent-backend';

i18n
  .use(Fluent)
  .use(Backend)
  .use(LanguageDetector)
  .use(initReactI18next)
  .init({
    fallbackLng: 'en-US',

    ns: ['translations'],
    defaultNS: 'translations',

    debug: true,

    interpolation: {
      escapeValue: false,
    },

    react: {
      wait: true,
    },
  });

export default i18n;
```

And this is one example from the .ftl files:

```
emails =  
  { $unreadEmails ->
    [zero] You have no unread emails.
    [one] You have one unread email.
    *[other] You have { $unreadEmails } unread emails.
}
```

App.tsx is rendered using `withTranslation` HOC:

```
const App = withTranslation('translations')(InitialApp);
export default App;
```

Is this a sort of bug or should I configure zero as an exception?
And how could I manage intervals? For example I want numbers between 2 and 10 managed as [few]. Thanks in advance

**Comment by jamuhl** [comment]
Looking at the fluent docs having `[zero]` should be possible: https://projectfluent.org/fluent/guide/selectors.html

but wondering...we this not on our side - we just reuse the fluentBundle from fluent itself: https://github.com/i18next/i18next-fluent/blob/master/src/index.js#L105

**Comment by jamuhl** [comment]
but yes the test does not include test for zero...https://github.com/i18next/i18next-fluent/blob/master/test/fuent.spec.js#L7

so it might not work...if you like to digg deeper you might give it a go - else i will take a look sooner or later -> coming from i18next syntax this module has not my highest prio to be honest

**Comment by Cesco9525** [comment]
Thank you! Do you have any advice if I decide to "fix" this? Which files should I look into?

**Comment by jamuhl** [comment]
guess would be here: https://github.com/i18next/i18next-fluent/blob/master/src/index.js#L97

**Comment by jamuhl** [comment]
Just added tests and checked the docs again:

it's not `[zero]` but `[0]` in fluent: https://projectfluent.org/fluent/guide/functions.html -> NUMBER

**Comment by jamuhl** [comment]
https://github.com/i18next/i18next-fluent/commit/3a3cf620779730719b4f2c5770e5bba83ed7eb26#diff-2d73fc47841177811b8884c7c5e495cfR7

**Comment by Cesco9525** [comment]
I tried both with [0] and [zero] and I get the same result

**Comment by jamuhl** [comment]
The test does not fail...https://github.com/i18next/i18next-fluent/blob/master/test/fuent.spec.js#L86

**Comment by Cesco9525** [comment]
I know, I tried it, maybe it's something with some other library

**Comment by jamuhl** [comment]
@Cesco9525 I see nothing I could do from here - seems to work -> you will need to digg into it yourself finding the difference in your code.

**Comment by Cesco9525** [comment]
Turns out that [0] becomes [undefined], this is one log:
```
emails: "{ $unreadEmails ->
  [undefined] You have no unread emails.
  [one] You have one unread email.
 *[other] You have { $unreadEmails } unread emails.
}"
```

**Comment by jamuhl** [comment]
Sorry can't follow...when you call `i18next.t('emails', { unreadEmails: 0 })` 0 gets converted to `undefined` ?

**Comment by Cesco9525** [comment]
Yes, as you've seen it was an issue with [fluent_conv](https://github.com/locize/fluent_conv), thanks for your support!

**Comment by jamuhl** [comment]
@Cesco9525 you mean the PR? was merged and published...i18next-fluent@0.0.4 should also contain that

**Comment by Cesco9525** [comment]
Yes, I just updated my dependencies ;)
