### ISSUE TITLE
Using i18next-fluent with already loaded ftl string without i18next-fluent-backend

### ISSUE THREAD

**Issue by popovycholeg** [i18next/i18next-fluent#9]
I would like to use ftl translations for my microfronted app. I do not want to use `i18next-fluent-backend` since ftl string is already loaded differently as a string so, I do not like to make a request once more for part of the app.  From the documentation, it seems that I can use only [i18next-fluent](https://github.com/i18next/i18next-fluent/tree/master?tab=readme-ov-file#more-complete-sample), but it doesn't properly change tags numbering. It doesn't change tags numbering to follow[ i18next system](https://react.i18next.com/latest/trans-component#how-to-get-the-correct-translation-string)
`<1>Test1</1><2>Test2</2> => <0>Test1</0><1>Test2</1>`

Is it possible to use this repo with an already loaded ftlString?

<img width="375" alt="image" src="https://github.com/i18next/i18next-fluent/assets/38152098/ca839512-9094-4870-9861-6e28043831cb">

**Comment by adrai** [comment]
since it's fluent format you can't use it like that... 
i did not yet tried it, since afk, but check this old example: https://github.com/i18next/react-i18next/tree/master/example/v9.x.x/react-fluent

**Comment by popovycholeg** [comment]
Thanks, that is something that I'm referring to, it seems to work fine when I load `.ftl` files with `i18next-fluent-backend`, but seems that we can't use the fluent format as a raw string or convert it somehow.

**Comment by adrai** [comment]
Here an example: https://github.com/i18next/react-i18next/blob/master/example/react-fluent/src/i18n.js#L28

**Comment by popovycholeg** [comment]
I see that interpolation works. Seems that my project uses a different tags ordering system. So I need to post-process stings to make this convertation. `<1>Test1</1><2>Test2</2> => <0>Test1</0><1>Test2</1>`
Thanks for your assistance.
